### ISSUE TITLE
Missing metadata when I import the application image in the OpenShift Server

### ISSUE THREAD

**Issue by johnreytanquinco** [universityofadelaide/s2i-shepherd-drupal#3]
I was able to successfully create a running application image locally and now I want to push it to the OpenShift registry(server) but getting stuck with some issue.

I run `oc import-image <application-image>` after doing `oc login` and select project for it.

Now for some reasons it was actually imported(because I can see the image from the server) with some errors.
```

The import completed with errors.

Name:			opensocial-app
Namespace:		pi-sti
Created:		2 hours ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2017-07-27T09:27:33Z
Docker Pull Spec:	172.30.175.57:5000/pi-sti/opensocial-app
Unique Images:		0
Tags:			1

latest
  tagged from opensocial-app

  ! error: Import failed (Unauthorized): you may not have access to the Docker image "opensocial-app"
      2 hours ago
```

I've got two specific questions for this.
1. When accessing `docker images`, I can see that there is four images created with different images IDs.
**Which of them is the image stream and which is not?**
 - candidate
 - cadidate-testapp
 - and two unlabeled images

2. How can I be able to update the image on the OpenShift server?
I tried to issue `image-import` again but does not update it.

**Comment by johnreytanquinco** [comment]
The above steps(`oc import-image`) is not working. So to fix this, I should use the proper way of getting the application image into OpenShift registry.

Steps I followed:
1. SSH to server
2. Build and create the application image
3. Log in to Openshift registry
4. Tag the image
5. Push 

This will create an image stream in OpenShift.

**Comment by singularo** [comment]
We use a buildConfig that specifies it as the builder image, and it will be auto pulled and used. You may not need the build-key parts, which are because we have an authenticated repository.

This is all generated from the shepherd orchestrator: 
https://github.com/universityofadelaide/shepherd

But an exported example buildconfig:

```
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  name: yourrepo-develop
  namespace: myproject
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'yourrepo:develop'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: branchname
      uri: 'git@yourhost.com/yourrepo.git'
    secrets:
      - destinationDir: .
        secret:
          name: build-key
    sourceSecret:
      name: build-key
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: DockerImage
        name: uofa/s2i-shepherd-drupal
      incremental: true
      pullSecret:
        name: build-key
    type: Source
  triggers:
    - type: ConfigChange
status:
  lastVersion: 1
```
